name: Build
permissions:
  contents: write
on:
  push:
    branches:
      - '**'
    tags-ignore:
      - 'v*'
jobs:

  Test-Scripts:
    runs-on: windows-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v6

      - name: Test PowerShell scripts
        shell: pwsh
        run: |
          $pesterConfig = @{
            Run = @{
              Path = ".\tests\common.Tests.ps1"
              Exit = $true
            }
            TestResult = @{
              Enabled = $true
              OutputPath = "testResults.xml"
              OutputFormat = "NUnitXML"
            }
            Output = @{
              Verbosity = "Detailed"
            }
          }
          Invoke-Pester -Configuration $pesterConfig

      - name: Test Python scripts
        shell: pwsh
        working-directory: packages\common
        run: python -m unittest mkzip

      - name: Upload test results
        uses: actions/upload-artifact@v7
        with:
          name: Pester-Test-Results
          path: testResults.xml

  Build-Prerequisites:
    runs-on: windows-latest
    needs: Test-Scripts
    steps:

      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup MSYS2
        uses: msys2/setup-msys2@v2

      - name: Turn off git autocrlf
        shell: pwsh
        run: git config --global core.autocrlf false

      - name: Check OpenOCD repository
        shell: pwsh
        run: .\packages\common\build-id.ps1 openocd .\config\x64-compile.json >> $env:GITHUB_ENV

      - name: Cache OpenOCD build
        uses: actions/cache@v5
        with:
          path: build/openocd-install
          key: ${{ env.OPENOCD_BUILD_ID }}

      - name: Check riscv-gnu-toolchain repository
        shell: pwsh
        run: .\packages\common\build-id.ps1 riscv-gnu-toolchain .\config\x64-compile.json >> $env:GITHUB_ENV

      - name: Cache riscv-gnu-toolchain build
        uses: actions/cache@v5
        with:
          path: build/riscv-gnu-toolchain-install
          key: ${{ env.RISCV-GNU-TOOLCHAIN_BUILD_ID }}

      - name: Compile
        shell: pwsh
        run: |
          Set-StrictMode -Version Latest
          $ErrorActionPreference = 'Stop'
          $ProgressPreference = 'SilentlyContinue'

          subst P: .
          P:

          .\build.ps1 -CompileConfig .\config\x64-compile.json -MSYS2Path (msys2 -c 'cygpath -m /').TrimEnd('\/') -Target Download,Compile

      - name: Upload build artifacts
        uses: actions/upload-artifact@v7
        with:
          name: Build-x64
          path: |
            build/pico-sdk-tools
            build/openocd-install
            build/riscv-gnu-toolchain-install

  Build-Installer:
    runs-on: windows-latest
    needs: Build-Prerequisites
    strategy:
      fail-fast: false
      matrix:
        config: [x64, x64-standalone]
        build-type: [system]
        target: [Installer]
        include:
          - { config: x64-standalone, build-type: user, target: Installer }
          - { config: x64-standalone, build-type: user, target: Archive }
    steps:

      - name: Checkout
        uses: actions/checkout@v6

      - name: Turn off git autocrlf
        shell: pwsh
        run: git config --global core.autocrlf false

      - name: Download build artifacts
        uses: actions/download-artifact@v8
        with:
          name: Build-x64
          path: build

      - name: Build ${{ matrix.config }} ${{ matrix.target }} (${{ matrix.build-type }})
        shell: pwsh
        run: |
          Set-StrictMode -Version Latest
          $ErrorActionPreference = 'Stop'
          $ProgressPreference = 'SilentlyContinue'

          subst P: .
          P:

          .\build.ps1 -CompileConfig .\config\x64-compile.json -InstallerConfig .\config\${{ matrix.config }}.json -Compression zlib -BuildType ${{ matrix.build-type }} -Target Download,${{ matrix.target }}

      - name: Upload build artifacts
        uses: actions/upload-artifact@v7
        with:
          name: Package-${{ matrix.config }}-${{ matrix.build-type }}-${{ matrix.target }}
          path: bin/

  Test-Installer:
    runs-on: windows-latest
    needs: Build-Installer
    strategy:
      fail-fast: false
      matrix:
        winver: ['2025']
        config: [x64, x64-standalone]
        build-type: [system]
        target: [Installer]
        include:
          - { winver: '2025', config: x64-standalone, build-type: user, target: Installer }
          - { winver: '2025', config: x64-standalone, build-type: user, target: Archive }
    steps:

      - name: Checkout
        uses: actions/checkout@v6

      - name: Download installer artifact
        uses: actions/download-artifact@v8
        with:
          name: Package-${{ matrix.config }}-${{ matrix.build-type }}-${{ matrix.target }}
          path: bin

      - name: Test ${{ matrix.config }} (${{ matrix.build-type }})
        shell: pwsh
        run: docker run --rm -v "$(Get-Location):C:\repo" -w C:\repo
          mcr.microsoft.com/windows/servercore:ltsc${{ matrix.winver }}
          powershell -NoProfile -NonInteractive -ExecutionPolicy Bypass -File .\tests\setup.ps1

      - name: Upload installer logs
        uses: actions/upload-artifact@v7
        with:
          name: Installer-Logs-Windows-${{ matrix.winver }}-${{ matrix.config }}-${{ matrix.build-type }}
          path: logs/

  Publish-Release:
    runs-on: windows-latest
    needs: Build-Installer
    if: github.event_name == 'push'
    steps:

      - name: Checkout
        uses: actions/checkout@v6

      - name: Download installer artifact
        uses: actions/download-artifact@v8
        with:
          pattern: Package-*
          merge-multiple: true
          path: bin

      - name: Publish release
        shell: bash
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: .github/publish-release.sh
